/*
 * Autopsy Forensic Browser
 *
 * Copyright 2019 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sleuthkit.autopsy.communications.relationships;

import org.openide.explorer.ExplorerManager;
import org.openide.nodes.Node;

/**
 * Displays the propertied of a ContactNode in a PropertySheet.
 */
public final class ContactDetailsPane extends javax.swing.JPanel implements ExplorerManager.Provider {

    final private ExplorerManager explorerManager = new ExplorerManager();

    /**
     * Displays the propertied of a ContactNode in a PropertySheet.
     */
    public ContactDetailsPane() {
        initComponents();
        this.setEnabled(false);
        
        nameLabel.setText("");
    }

    /**
     * Sets the list of nodes for the property sheet.
     *
     * @param nodes List of nodes to set
     */
    public void setNode(Node[] nodes) {
        if (nodes != null && nodes.length == 1) {
            nameLabel.setText(nodes[0].getDisplayName());
            propertySheet.setNodes(nodes);
        } else {
            nameLabel.setText("");
            propertySheet.setNodes(null);
        }
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        nameLabel.setEnabled(enabled);
        propertySheet.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        messageContentViewer1 = new org.sleuthkit.autopsy.contentviewers.MessageContentViewer();
        nameLabel = new javax.swing.JLabel();
        propertySheet = new org.openide.explorer.propertysheet.PropertySheet();

        setLayout(new java.awt.GridBagLayout());

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(ContactDetailsPane.class, "ContactDetailsPane.nameLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 15, 15);
        add(nameLabel, gridBagConstraints);

        propertySheet.setDescriptionAreaVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 15, 16, 15);
        add(propertySheet, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.sleuthkit.autopsy.contentviewers.MessageContentViewer messageContentViewer1;
    private javax.swing.JLabel nameLabel;
    private org.openide.explorer.propertysheet.PropertySheet propertySheet;
    // End of variables declaration//GEN-END:variables
}
