/*
 * Autopsy Forensic Browser
 *
 * Copyright 2019 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sleuthkit.autopsy.geolocation;

import java.awt.Color;
import java.io.File;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.UrlValidator;
import org.jxmapviewer.OSMTileFactoryInfo;
import org.jxmapviewer.viewer.TileFactoryInfo;
import org.jxmapviewer.viewer.util.GeoUtil;
import org.netbeans.spi.options.OptionsPanelController;
import org.openide.util.NbBundle.Messages;
import org.sleuthkit.autopsy.casemodule.GeneralFilter;
import org.sleuthkit.autopsy.core.UserPreferences;
import org.sleuthkit.autopsy.corecomponents.OptionsPanel;

/**
 * A panel to allow the user to set the custom properties of the geolocation
 * window.
 *
 */
final class GeolocationSettingsPanel extends javax.swing.JPanel implements OptionsPanel {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new GeolocationSettingsPanel
     */
    GeolocationSettingsPanel() {
        initComponents();
        updateControlState();
    }

    @Override
    public void store() {
        UserPreferences.setGeolocationTileOption(getServerOption().getValue());
        UserPreferences.setGeolocationOsmZipPath(osmZipFileField.getText());
        UserPreferences.setGeolocationOsmServerAddress(tileServerFiled.getText());
    }

    @Override
    public void load() {
        tileServerFiled.setText(UserPreferences.getGeolocationOsmServerAddress());
        osmZipFileField.setText(UserPreferences.getGeolocationOsmZipPath());
        switch (GeolocationTileOption.getOptionForValue(UserPreferences.getGeolocationtTileOption())) {
            case ONLINE_USER_DEFINED_OSM_SERVER:
                tileServerButton.setSelected(true);
                break;
            case OFFLINE_OSM_ZIP:
                osmZipButton.setSelected(true);
                break;
            default:
                defaultButton.setSelected(true);
                break;
        }

        updateControlState();
    }

    /**
     * Update the state of the tile server options based on the radio button
     * selection state.
     */
    private void updateControlState() {
        tileServerFiled.setEnabled(tileServerButton.isSelected());
        serverTestButton.setEnabled(tileServerButton.isSelected());
        osmZipFileField.setEnabled(osmZipButton.isSelected());
        osmZipFileBrowseButton.setEnabled(osmZipButton.isSelected());
    }

    /**
     * Returns the GEOLOCATION_TILE_OPTION based on the selection state of the
     * option radio buttons.
     *
     * @return Current GEOLOCATION_TILE_OPTION
     */
    private GeolocationTileOption getServerOption() {
        if (tileServerButton.isSelected()) {
            return GeolocationTileOption.ONLINE_USER_DEFINED_OSM_SERVER;
        } else if (osmZipButton.isSelected()) {
            return GeolocationTileOption.OFFLINE_OSM_ZIP;
        }
        return GeolocationTileOption.ONLINE_DEFAULT_SERVER;
    }

    /**
     * Tests the validity of the given tile server address.
     *
     * This test assumes the server is able to serve up at least one tile, the
     * tile at x=1, y=1 with a zoom level of 1. This tile should be the whole
     * global.
     *
     * @param url String url to tile server. The string does not have to be
     *            prefixed with http://
     *
     * @return True if the server was successfully contacted.
     */
    private boolean testOSMServer(String url) {
        TileFactoryInfo info = new OSMTileFactoryInfo("User Defined Server", url); //NON-NLS
        return GeoUtil.isValidTile(1, 1, 1, info);
    }
    
    void cancelChanges() {
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.ButtonGroup buttonGroup = new javax.swing.ButtonGroup();
        javax.swing.JPanel tilePane = new javax.swing.JPanel();
        defaultButton = new javax.swing.JRadioButton();
        tileServerButton = new javax.swing.JRadioButton();
        tileServerFiled = new javax.swing.JTextField();
        osmZipButton = new javax.swing.JRadioButton();
        osmZipFileField = new javax.swing.JTextField();
        osmZipFileBrowseButton = new javax.swing.JButton();
        serverTestButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        tilePane.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(GeolocationSettingsPanel.class, "GeolocationSettingsPanel.tilePane.border.title"))); // NOI18N
        tilePane.setLayout(new java.awt.GridBagLayout());

        buttonGroup.add(defaultButton);
        defaultButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(defaultButton, org.openide.util.NbBundle.getMessage(GeolocationSettingsPanel.class, "GeolocationSettingsPanel.defaultButton.text")); // NOI18N
        defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        tilePane.add(defaultButton, gridBagConstraints);

        buttonGroup.add(tileServerButton);
        org.openide.awt.Mnemonics.setLocalizedText(tileServerButton, org.openide.util.NbBundle.getMessage(GeolocationSettingsPanel.class, "GeolocationSettingsPanel.tileServerButton.text")); // NOI18N
        tileServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tileServerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        tilePane.add(tileServerButton, gridBagConstraints);

        tileServerFiled.setText(org.openide.util.NbBundle.getMessage(GeolocationSettingsPanel.class, "GeolocationSettingsPanel.tileServerFiled.text")); // NOI18N
        tileServerFiled.setPreferredSize(new java.awt.Dimension(300, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        tilePane.add(tileServerFiled, gridBagConstraints);

        buttonGroup.add(osmZipButton);
        org.openide.awt.Mnemonics.setLocalizedText(osmZipButton, org.openide.util.NbBundle.getMessage(GeolocationSettingsPanel.class, "GeolocationSettingsPanel.osmZipButton.text")); // NOI18N
        osmZipButton.setActionCommand(org.openide.util.NbBundle.getMessage(GeolocationSettingsPanel.class, "GeolocationSettingsPanel.osmZipButton.actionCommand")); // NOI18N
        osmZipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osmZipButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        tilePane.add(osmZipButton, gridBagConstraints);

        osmZipFileField.setText(org.openide.util.NbBundle.getMessage(GeolocationSettingsPanel.class, "GeolocationSettingsPanel.osmZipFileField.text")); // NOI18N
        osmZipFileField.setPreferredSize(new java.awt.Dimension(300, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        tilePane.add(osmZipFileField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(osmZipFileBrowseButton, org.openide.util.NbBundle.getMessage(GeolocationSettingsPanel.class, "GeolocationSettingsPanel.osmZipFileBrowseButton.text")); // NOI18N
        osmZipFileBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osmZipFileBrowseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 9, 9);
        tilePane.add(osmZipFileBrowseButton, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(serverTestButton, org.openide.util.NbBundle.getMessage(GeolocationSettingsPanel.class, "GeolocationSettingsPanel.serverTestButton.text")); // NOI18N
        serverTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverTestButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 9, 9);
        tilePane.add(serverTestButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(tilePane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void osmZipFileBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osmZipFileBrowseButtonActionPerformed
        JFileChooser fileWindow = new JFileChooser();
        fileWindow.setFileSelectionMode(JFileChooser.FILES_ONLY);
        GeneralFilter fileFilter = new GeneralFilter(Arrays.asList(".zip"), "Zips (*.zip)"); //NON-NLS
        fileWindow.setDragEnabled(false);
        fileWindow.setFileFilter(fileFilter);
        fileWindow.setMultiSelectionEnabled(false);
        int returnVal = fileWindow.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File zipFile = fileWindow.getSelectedFile();
            osmZipFileField.setForeground(Color.BLACK);
            osmZipFileField.setText(zipFile.getAbsolutePath());
            firePropertyChange(OptionsPanelController.PROP_CHANGED, null, null);
        }
    }//GEN-LAST:event_osmZipFileBrowseButtonActionPerformed

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        updateControlState();
        firePropertyChange(OptionsPanelController.PROP_CHANGED, null, null);
    }//GEN-LAST:event_defaultButtonActionPerformed

    private void tileServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tileServerButtonActionPerformed
        updateControlState();
        firePropertyChange(OptionsPanelController.PROP_CHANGED, null, null);
    }//GEN-LAST:event_tileServerButtonActionPerformed

    private void osmZipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osmZipButtonActionPerformed
        updateControlState();
        firePropertyChange(OptionsPanelController.PROP_CHANGED, null, null);
    }//GEN-LAST:event_osmZipButtonActionPerformed

    @Messages({
        "GeolocationSettingsPanel_malformed_url_message=The supplies OSM tile server address is invalid.\nPlease supply a well formed url prefixed with http://",
        "GeolocationSettingsPanel_malformed_url_message_tile=Malformed URL",
        "GeolocationSettingsPanel_osm_server_test_fail_message=OSM tile server test failed.\nUnable to connect to server.",
        "GeolocationSettingsPanel_osm_server_test_fail_message_title=Error",
        "GeolocationSettingsPanel_osm_server_test_success_message=The provide OSM tile server address is valid.",
        "GeolocationSettingsPanel_osm_server_test_success_message_title=Success",})
    private void serverTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverTestButtonActionPerformed
        String address = tileServerFiled.getText();
        String message = Bundle.GeolocationSettingsPanel_osm_server_test_fail_message();
        String title = Bundle.GeolocationSettingsPanel_osm_server_test_fail_message_title();

        String[] schemes = {"http", "https"}; //NON-NLS
        UrlValidator urlValidator = new UrlValidator(schemes);
        if (!urlValidator.isValid(address)) {
            message = Bundle.GeolocationSettingsPanel_malformed_url_message();
            title = Bundle.GeolocationSettingsPanel_malformed_url_message_tile();
        } else if (testOSMServer(address)) {
            message = Bundle.GeolocationSettingsPanel_osm_server_test_success_message();
            title = Bundle.GeolocationSettingsPanel_osm_server_test_success_message_title();
        }

        JOptionPane.showMessageDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_serverTestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton defaultButton;
    private javax.swing.JRadioButton osmZipButton;
    private javax.swing.JButton osmZipFileBrowseButton;
    private javax.swing.JTextField osmZipFileField;
    private javax.swing.JButton serverTestButton;
    private javax.swing.JRadioButton tileServerButton;
    private javax.swing.JTextField tileServerFiled;
    // End of variables declaration//GEN-END:variables

    /**
     * Tile server option enum. The enum was given values to simplify the
     * storing of the user preference for a particular option.
     */
    enum GeolocationTileOption{
        ONLINE_DEFAULT_SERVER(0),
        ONLINE_USER_DEFINED_OSM_SERVER(1),
        OFFLINE_OSM_ZIP(2);

        private final int value;

        GeolocationTileOption(int value) {
            this.value = value;
        }

        int getValue() {
            return value;
        }

        static GeolocationTileOption getOptionForValue(int value) {
            for (GeolocationTileOption option : GeolocationTileOption.values()) {
                if (option.getValue() == value) {
                    return option;
                }
            }

            return ONLINE_DEFAULT_SERVER;
        }
    }

}
