/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.ingest.runIngestModuleWizard;

import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import org.sleuthkit.autopsy.ingest.IngestProfileMap;
import org.sleuthkit.autopsy.ingest.IngestProfileMap.IngestProfile;

public final class IngestProfileSelectionPanel extends JPanel implements ItemListener {

    private static final String CUSTOM_SETTINGS_TEXT = "Custom Settings - configure individual module settings";
    RunIngestModuleWizardWizardPanel1 wizardPanel;
    String selectedProfile;
    List<IngestProfile> elements = Collections.emptyList();

    /**
     * Creates new form runIngestModuleWizardVisualPanel1
     */
    public IngestProfileSelectionPanel(RunIngestModuleWizardWizardPanel1 panel) {
        initComponents();
        //WJS-TODO figure out how to get width of writable area, if text length greater than width. Trim text to width minus 3 chars in length and then add ... to the end
        wizardPanel = panel;
        elements = getElements();
        customSettings = new JRadioButton(CUSTOM_SETTINGS_TEXT, true);
        customSettings.setName(RunIngestModuleWizardWizardIterator.getDefaultContext());

        customSettings.setRolloverEnabled(true);
        customSettings.setToolTipText(CUSTOM_SETTINGS_TEXT);
        buttonGroup1.add(customSettings);
        jPanel1.add(customSettings);

        selectedProfile = customSettings.getName();
        String tempDescription = "REPLACE THIS WITH DESCRIPTION";

        for (IngestProfile profile : elements) {
            JRadioButton myRadio = new JRadioButton(profile.toString() + tempDescription);
            myRadio.setName(profile.toString());
            myRadio.setToolTipText(tempDescription);
            myRadio.addItemListener(this);
            buttonGroup1.add(myRadio);
            jPanel1.add(myRadio);
        }

    }

    @Override
    public String getName() {
        return "Ingest Profile Selection";
    }

    List<IngestProfile> getElements() {
        if (elements.isEmpty()) {
            fetchListContents();
        }
        return elements;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(IngestProfileSelectionPanel.class, "IngestProfileSelectionPanel.jButton1.text")); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(IngestProfileSelectionPanel.class, "IngestProfileSelectionPanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 523, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    boolean hasNextPanel = true;
    private JRadioButton customSettings;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        for (Component rButton : jPanel1.getComponents()) {
            JRadioButton jrb = (JRadioButton) rButton;
            if (jrb.isSelected()) {
                selectedProfile = jrb.getName();
                break;
            }
        }

        boolean hadNextPanel = hasNextPanel;
        hasNextPanel = !hasNextPanel;
        System.out.println(
                "SWITCHED VALUES, VALUE NOW:" + hasNextPanel);
        wizardPanel.fireChangeEvent();
        this.firePropertyChange(
                "LAST_ENABLED", hadNextPanel, hasNextPanel);
    }

    private void fetchListContents() {
        elements = new ArrayList<IngestProfile>();
        elements.addAll(new IngestProfileMap().getIngestProfileMap().values());
    }
}
