/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.url.analytics;

import org.openide.util.NbBundle.Messages;

/**
 *
 * @author gregd
 */
public class AddEditCategoryDialog extends javax.swing.JDialog {

    private boolean changed = false;

    /**
     * Creates new form AddEditCategoryDialog
     */
    public AddEditCategoryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * @return The string value for the name in the input field if Ok pressed or
     * null if not.
     */
    DomainCategory getValue() {
        return new DomainCategory(domainSuffixTextField.getText(), categoryTextField.getText());
    }

    /**
     * @return Whether or not the value has been changed and the user pressed
     * okay to save the new value.
     */
    boolean isChanged() {
        return changed;
    }
    
        /**
     * When the text field is updated, this method is called.
     *
     * @param newNameValue
     */
    @Messages({
        "# {0} - maxSuffixLen",
        "AddEditCategoryDialog_onValueUpdate_badSuffix=Please provide a domain suffix that is no more than {0} characters.",
        "# {0} - maxCategoryLen",
        "AddEditCategoryDialog_onValueUpdate_badCategory=Please provide a domain suffix that is no more than {0} characters.",
    })
    void onValueUpdate(String suffixStr, String categoryStr) {
        
        String safeSuffixStr = suffixStr == null ? "" : suffixStr;
        String safeCategoryStr = categoryStr == null ? "" : categoryStr;
        
        // update input text field if it is not the same.
        if (!safeCategoryStr.equals(categoryTextField.getText())) {
            categoryTextField.setText(safeCategoryStr);
        }
        
        if (!safeSuffixStr.equals(domainSuffixTextField.getText())) {
            domainSuffixTextField.setText(safeSuffixStr);
        }
        
        if (safeSuffixStr.length() == 0 || safeSuffixStr.length() > WebCategoriesManager.getMaxDomainSuffixLength()) {
            
        } else if (safeCategoryStr.length() == 0 || safeCategoryStr.length() > WebCategoriesManager.getMaxCategoryLength()) {
            
        }  

        // validate text input against invariants setting validation 
        // message and whether or not okay button is enabled accordingly.
//        String validationMessage = HostNameValidator.getValidationMessage(
//                newNameValue, initialHost == null ? null : initialHost.getName(), hostNamesSanitized);
//        
//        okButton.setEnabled(validationMessage == null);
//        validationLabel.setText(validationMessage == null ? "" : validationMessage);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryTextField = new javax.swing.JTextField();
        domainSuffixTextField = new javax.swing.JTextField();
        javax.swing.JLabel categoryLabel = new javax.swing.JLabel();
        javax.swing.JLabel domainSuffixLabel = new javax.swing.JLabel();
        validationLabel = new javax.swing.JLabel();
        javax.swing.JButton cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        categoryLabel.setText("Category:");

        domainSuffixLabel.setText("Domain Suffix:");

        validationLabel.setForeground(java.awt.Color.RED);
        validationLabel.setText(" ");
        validationLabel.setToolTipText("");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(domainSuffixLabel)
                            .addComponent(categoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(categoryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(domainSuffixTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 216, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel)
                            .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(domainSuffixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(domainSuffixLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        this.changed = true;
        dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.changed = false;
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JTextField domainSuffixTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel validationLabel;
    // End of variables declaration//GEN-END:variables
}
