/*
 * 
 * Autopsy Forensic Browser
 * 
 * Copyright 2018 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sleuthkit.autopsy.commonfilesearch;

import java.util.Map;
import org.sleuthkit.autopsy.datamodel.DisplayableItemNode;
import org.sleuthkit.datamodel.AbstractFile;

/**
 * Defines types which can be used to get some sort of File Instance node (a
 * child of the MD5Node) for use in the common files tree table.
 */
public abstract class CommonAttributeInstanceNodeGenerator {

    protected Long abstractFileObjectId;
    protected Map<Long, AbstractFile> cachedFiles;
    String caseName;
    String dataSource;

    public CommonAttributeInstanceNodeGenerator(Long abstractFileReference, Map<Long, AbstractFile> cachedFiles, String dataSource, String caseName) {
        this.abstractFileObjectId = abstractFileReference;
        this.cachedFiles = cachedFiles;
        this.caseName = caseName;
        this.dataSource = dataSource;
    }
    
    public CommonAttributeInstanceNodeGenerator(Map<Long, AbstractFile> cachedFiles) {
        this.abstractFileObjectId = -1L;
        this.cachedFiles = cachedFiles;
        this.caseName = "";
        this.dataSource = "";
    }

    /**
     * Grab a cached instance of the AbstractFile or grab one from the
     * SleuthkitCase. Use this in implementations of <code>generateNode</code>.
     *
     * @param objectId
     * @param cachedFiles
     * @return AbstractFile which is identical to the file instance generated by
     * implementations of this object
     */
    protected AbstractFile lookupOrCreateAbstractFile() {
        if (cachedFiles.containsKey(this.abstractFileObjectId)) {
            return cachedFiles.get(this.abstractFileObjectId);
        } else {
            AbstractFile file = this.loadFileFromSleuthkitCase();
            cachedFiles.put(this.abstractFileObjectId, file);
            return file;
        }
    }

    /**
     * 
     * @return 
     */
    abstract protected AbstractFile loadFileFromSleuthkitCase();
    
    /**
     * Create a list of nodes which are a child of the MD5Node, to be used to display a
     * row in the tree table
     *
     * @return child row node
     */
    public abstract DisplayableItemNode[] generateNodes();

    public String getCaseName() {
        return this.caseName;
    }

    /**
     * Get string name of the data source where this instance appears.
     *
     * @return
     */
    public String getDataSource() {

        /**
         * Even though we could get this from the CR record or the AbstractFile,
         * we want to avoid getting it from the AbstractFile because it would be
         * an extra database roundtrip.
         */
        return this.dataSource;
    }

    public Long getIdenticalFileSleuthkitCaseObjectID() {
        return this.abstractFileObjectId;
    }

}
