/*
 * Autopsy Forensic Browser
 *
 * Copyright 2019 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sleuthkit.autopsy.contentviewers;

import java.awt.Component;
import java.awt.Cursor;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import org.apache.tika.parser.txt.CharsetDetector;
import org.apache.tika.parser.txt.CharsetMatch;
import org.openide.util.NbBundle;
import org.openide.windows.WindowManager;
import org.sleuthkit.autopsy.coreutils.Logger;
import org.sleuthkit.datamodel.AbstractFile;
import org.sleuthkit.datamodel.TskCoreException;

/**
 * A file content viewer for HTML files.
 */
@SuppressWarnings("PMD.SingularField") // UI widgets cause lots of false positives
final class HtmlViewer extends javax.swing.JPanel implements FileTypeViewer {

    private static final long serialVersionUID = 1L;
    private static final Logger logger = Logger.getLogger(HtmlViewer.class.getName());
    private static final String[] SUPPORTED_MIMETYPES = new String[]{
        "text/html",
        "application/xhtml+xml"
    };
    private final org.sleuthkit.autopsy.contentviewers.HtmlPanel htmlPanel = new org.sleuthkit.autopsy.contentviewers.HtmlPanel();

    /**
     * Creates new form HtmlViewerPanel
     */
    HtmlViewer() {
        initComponents();
        this.add(htmlPanel);
    }

    /**
     * Retrieve the HTML text content from the supplied file.
     *
     * @param abstractFile The file to read.
     *
     * @return The text content of the file.
     */
    @NbBundle.Messages({
        "HtmlViewer_file_error=This file is missing or unreadable.",
        "HtmlViewer_encoding_error=This file has unsupported encoding"})
    private String getHtmlText(AbstractFile abstractFile) {
        try {
            int fileSize = (int) abstractFile.getSize();
            byte[] buffer = new byte[fileSize];
            abstractFile.read(buffer, 0, fileSize);
            CharsetMatch match = new CharsetDetector().setText(buffer).detect();
            if (match != null) {
                return new String(buffer, match.getName());
            } else {
                return new String(buffer);
            }
        } catch (TskCoreException ex) {
            logger.log(Level.SEVERE, String.format("Unable to read from file '%s' (id=%d).",
                    abstractFile.getName(), abstractFile.getId()), ex);
            return String.format("<p>%s</p>", Bundle.HtmlViewer_file_error());
        } catch (UnsupportedEncodingException ex) {
            logger.log(Level.SEVERE, String.format("Unsupported encoding for file '%s' (id=%d).",
                    abstractFile.getName(), abstractFile.getId()), ex);
            return String.format("<p>%s</p>", Bundle.HtmlViewer_encoding_error());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public List<String> getSupportedMIMETypes() {
        return Arrays.asList(SUPPORTED_MIMETYPES);
    }

    @Override
    public void setFile(AbstractFile file) {
        WindowManager.getDefault().getMainWindow().setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        htmlPanel.setHtmlText(getHtmlText(file));
        WindowManager.getDefault().getMainWindow().setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }

    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public void resetComponent() {
        htmlPanel.reset();
    }

    @Override
    public boolean isSupported(AbstractFile file) {
        return true;
    }
}
