/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.discovery;

import org.sleuthkit.autopsy.centralrepository.datamodel.CentralRepository;

/**
 *
 * @author wschaefer
 */
final class DocumentFilterPanel extends AbstractFiltersPanel {

    private static final long serialVersionUID = 1L;
      private static final FileSearchData.FileType FILE_TYPE = FileSearchData.FileType.DOCUMENTS;

    /**
     * Creates new form DocumentFilterPanel
     */
    DocumentFilterPanel() {
        super();
        initComponents();
        addFilter(new SizeFilterPanel(FileSearchData.FileType.DOCUMENTS), false, null, 0);
        addFilter(new DataSourceFilterPanel(), false, null, 0);
        int[] pastOccurrencesIndices;
        if (!CentralRepository.isEnabled()) {
            pastOccurrencesIndices = new int[]{0};
        } else {
            pastOccurrencesIndices = new int[]{1, 2, 3, 4, 5, 6, 7};
        }
        addFilter(new PastOccurrencesFilterPanel(), true, pastOccurrencesIndices, 0);
        addFilter(new HashSetFilterPanel(), false, null, 1);
        addFilter(new InterestingItemsFilterPanel(), false, null, 1);
        addFilter(new ObjectDetectedFilterPanel(), false, null, 1);
        addFilter(new ParentFolderFilterPanel(), false, null, 1);
        addPanelsToScrollPane(documentsFiltersSplitPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        documentFiltersScrollPane = new javax.swing.JScrollPane();
        documentFiltersPanel = new javax.swing.JPanel();
        documentsFiltersSplitPane = new javax.swing.JSplitPane();

        setLayout(new java.awt.BorderLayout());

        documentFiltersPanel.setLayout(new java.awt.BorderLayout());

        documentsFiltersSplitPane.setResizeWeight(0.5);
        documentFiltersPanel.add(documentsFiltersSplitPane, java.awt.BorderLayout.CENTER);

        documentFiltersScrollPane.setViewportView(documentFiltersPanel);

        add(documentFiltersScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    @Override
    FileSearchData.FileType getFileType() {
        return FILE_TYPE;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel documentFiltersPanel;
    private javax.swing.JScrollPane documentFiltersScrollPane;
    private javax.swing.JSplitPane documentsFiltersSplitPane;
    // End of variables declaration//GEN-END:variables

}
