/*
 * Autopsy Forensic Browser
 *
 * Copyright 2022 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sleuthkit.autopsy.filesearch;

import java.awt.event.ActionListener;
import org.sleuthkit.datamodel.TskData;

class DeletedFilesSearchPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    
    private final static String ALL_DELETED_CONTENT_QUERY = "( "
                + "(dir_flags = " + TskData.TSK_FS_NAME_FLAG_ENUM.UNALLOC.getValue() //NON-NLS
                + " OR " //NON-NLS
                + "meta_flags = " + TskData.TSK_FS_META_FLAG_ENUM.ORPHAN.getValue() //NON-NLS
                + ")"
                + " AND type = " + TskData.TSK_DB_FILES_TYPE_ENUM.FS.getFileType() //NON-NLS
                + " )"
                + " OR type = " + TskData.TSK_DB_FILES_TYPE_ENUM.CARVED.getFileType() //NON-NLS
                + " OR (dir_flags = " + TskData.TSK_FS_NAME_FLAG_ENUM.UNALLOC.getValue()
                + " AND type = " + TskData.TSK_DB_FILES_TYPE_ENUM.LAYOUT_FILE.getFileType() + " )";

    /**
     * Creates new form DeletedFilesSearchPanel
     */
    DeletedFilesSearchPanel() {
        initComponents();
    }
    
    boolean isDeletedFileSelected() {
        return deletedCheckbox.isSelected();
    }
    
    void setDeletedFileSelected(boolean selected) {
        deletedCheckbox.setSelected(selected);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        deletedCheckbox = new javax.swing.JCheckBox();

        setMinimumSize(new java.awt.Dimension(337, 49));
        setPreferredSize(new java.awt.Dimension(337, 49));
        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(deletedCheckbox, org.openide.util.NbBundle.getMessage(DeletedFilesSearchPanel.class, "DeletedFilesSearchPanel.deletedCheckbox.text")); // NOI18N
        deletedCheckbox.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(deletedCheckbox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox deletedCheckbox;
    // End of variables declaration//GEN-END:variables
    static final class DeletedFileSearchFilter extends AbstractFileSearchFilter<DeletedFilesSearchPanel> {

        DeletedFileSearchFilter() {
            super(new DeletedFilesSearchPanel());
        }
        
        @Override
        public boolean isEnabled() {
            return true;
        }

        @Override
        public boolean isValid() {
            return true;
        }

        @Override
        public String getPredicate() throws FilterValidationException {
            if (getComponent().isDeletedFileSelected()) {
                return ALL_DELETED_CONTENT_QUERY;
            }
            
            return "";
        }

        @Override
        public void addActionListener(ActionListener l) {
            
        }
        
    }


}
