/*
 * Autopsy Forensic Browser
 *
 * Copyright 2011-2021 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sleuthkit.autopsy.contentviewers.textcontentviewer;

import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import org.openide.util.NbBundle;
import org.sleuthkit.autopsy.coreutils.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import org.apache.commons.lang3.StringUtils;
import org.openide.util.NbBundle.Messages;
import org.sleuthkit.autopsy.coreutils.StringExtract;
import org.sleuthkit.autopsy.coreutils.StringExtract.StringExtractResult;
import org.sleuthkit.autopsy.coreutils.StringExtract.StringExtractUnicodeTable.SCRIPT;
import org.sleuthkit.autopsy.datamodel.StringContent;
import org.sleuthkit.autopsy.guiutils.WrapLayout;
import org.sleuthkit.datamodel.Content;
import org.sleuthkit.datamodel.TskCoreException;

/**
 * Viewer displays strings extracted from contents.
 */
@SuppressWarnings("PMD.SingularField") // UI widgets cause lots of false positives
public class StringsContentPanel extends javax.swing.JPanel {

    private static long currentOffset = 0;
    private static final long PAGE_LENGTH = 16384;
    private static final long serialVersionUID = 1L;
    private final byte[] data = new byte[(int) PAGE_LENGTH];
    private static int currentPage = 1;
    private Content dataSource;
    private static final Logger logger = Logger.getLogger(StringsContentPanel.class.getName());

    private SwingWorker<String, Void> worker;

    /**
     * Creates new form StringsTextViewer
     */
    public StringsContentPanel() {
        initComponents();
        customizeComponents();
        this.resetDisplay();
    }

    private void customizeComponents() {
        outputViewPane.setComponentPopupMenu(rightClickMenu);
        ActionListener actList = (ActionEvent e) -> {
            JMenuItem jmi = (JMenuItem) e.getSource();
            if (jmi.equals(copyMenuItem)) {
                outputViewPane.copy();
            } else if (jmi.equals(selectAllMenuItem)) {
                outputViewPane.selectAll();
            }
        };
        copyMenuItem.addActionListener(actList);
        selectAllMenuItem.addActionListener(actList);

        List<SCRIPT> supportedScripts = StringExtract.getSupportedScripts();
        supportedScripts.forEach((s) -> {
            languageCombo.addItem(s);
        });

        // use wrap layout for better component wrapping
        WrapLayout layout = new WrapLayout(0, 5);
        layout.setOppositeAligned(Arrays.asList(panelScriptSelect));
        controlPanel.setLayout(layout);

    }

    final void resetDisplay() {
        // clear / reset the fields
        currentPage = 1;
        currentOffset = 0;
        this.dataSource = null;
        currentPageLabel.setText("1");
        totalPageLabel.setText("");
        prevPageButton.setEnabled(false);
        nextPageButton.setEnabled(false);
        outputViewPane.setText(""); // reset the output view
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightClickMenu = new javax.swing.JPopupMenu();
        copyMenuItem = new javax.swing.JMenuItem();
        selectAllMenuItem = new javax.swing.JMenuItem();
        controlPanel = new javax.swing.JPanel();
        javax.swing.JPanel panelPageOfCount = new javax.swing.JPanel();
        pageLabel = new javax.swing.JLabel();
        javax.swing.JSeparator jSepMed1 = new javax.swing.JSeparator();
        currentPageLabel = new javax.swing.JLabel();
        javax.swing.JSeparator jSepMed2 = new javax.swing.JSeparator();
        ofLabel = new javax.swing.JLabel();
        javax.swing.JSeparator jSepMed3 = new javax.swing.JSeparator();
        totalPageLabel = new javax.swing.JLabel();
        javax.swing.JSeparator jSepMed4 = new javax.swing.JSeparator();
        javax.swing.JPanel panelPageNextPrevButton = new javax.swing.JPanel();
        pageLabel2 = new javax.swing.JLabel();
        javax.swing.JSeparator jSepMed5 = new javax.swing.JSeparator();
        prevPageButton = new javax.swing.JButton();
        nextPageButton = new javax.swing.JButton();
        javax.swing.JSeparator jSepMed6 = new javax.swing.JSeparator();
        javax.swing.JPanel panelGoToPage = new javax.swing.JPanel();
        goToPageLabel = new javax.swing.JLabel();
        javax.swing.JSeparator jSepSm1 = new javax.swing.JSeparator();
        goToPageTextField = new javax.swing.JTextField();
        javax.swing.JSeparator jSepMed7 = new javax.swing.JSeparator();
        panelScriptSelect = new javax.swing.JPanel();
        languageLabel = new javax.swing.JLabel();
        javax.swing.JSeparator jSepSm2 = new javax.swing.JSeparator();
        languageCombo = new javax.swing.JComboBox<>();
        outputScrollPane = new javax.swing.JScrollPane();
        outputViewPane = new javax.swing.JTextPane();

        copyMenuItem.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.copyMenuItem.text")); // NOI18N
        rightClickMenu.add(copyMenuItem);

        selectAllMenuItem.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.selectAllMenuItem.text")); // NOI18N
        rightClickMenu.add(selectAllMenuItem);

        setMinimumSize(new java.awt.Dimension(250, 5));
        setPreferredSize(new java.awt.Dimension(250, 58));
        setLayout(new java.awt.BorderLayout());

        controlPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        panelPageOfCount.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        pageLabel.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.pageLabel.text_1")); // NOI18N
        pageLabel.setMaximumSize(new java.awt.Dimension(33, 25));
        pageLabel.setMinimumSize(new java.awt.Dimension(33, 25));
        pageLabel.setPreferredSize(new java.awt.Dimension(32, 25));
        panelPageOfCount.add(pageLabel);

        jSepMed1.setPreferredSize(new java.awt.Dimension(5, 0));
        panelPageOfCount.add(jSepMed1);

        currentPageLabel.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.currentPageLabel.text_1")); // NOI18N
        panelPageOfCount.add(currentPageLabel);

        jSepMed2.setPreferredSize(new java.awt.Dimension(5, 0));
        panelPageOfCount.add(jSepMed2);

        ofLabel.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.ofLabel.text_1")); // NOI18N
        ofLabel.setMaximumSize(new java.awt.Dimension(11, 25));
        ofLabel.setMinimumSize(new java.awt.Dimension(11, 25));
        ofLabel.setPreferredSize(new java.awt.Dimension(11, 25));
        panelPageOfCount.add(ofLabel);

        jSepMed3.setPreferredSize(new java.awt.Dimension(5, 0));
        panelPageOfCount.add(jSepMed3);

        totalPageLabel.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.totalPageLabel.text_1")); // NOI18N
        totalPageLabel.setMaximumSize(new java.awt.Dimension(25, 25));
        totalPageLabel.setMinimumSize(new java.awt.Dimension(25, 25));
        totalPageLabel.setPreferredSize(new java.awt.Dimension(25, 25));
        panelPageOfCount.add(totalPageLabel);

        jSepMed4.setPreferredSize(new java.awt.Dimension(5, 0));
        panelPageOfCount.add(jSepMed4);

        controlPanel.add(panelPageOfCount);

        panelPageNextPrevButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        pageLabel2.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.pageLabel2.text")); // NOI18N
        pageLabel2.setMaximumSize(new java.awt.Dimension(29, 25));
        pageLabel2.setMinimumSize(new java.awt.Dimension(29, 25));
        pageLabel2.setPreferredSize(new java.awt.Dimension(29, 25));
        panelPageNextPrevButton.add(pageLabel2);

        jSepMed5.setPreferredSize(new java.awt.Dimension(5, 0));
        panelPageNextPrevButton.add(jSepMed5);

        prevPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sleuthkit/autopsy/corecomponents/btn_step_back.png"))); // NOI18N
        prevPageButton.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.prevPageButton.text")); // NOI18N
        prevPageButton.setBorderPainted(false);
        prevPageButton.setContentAreaFilled(false);
        prevPageButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sleuthkit/autopsy/corecomponents/btn_step_back_disabled.png"))); // NOI18N
        prevPageButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        prevPageButton.setMaximumSize(new java.awt.Dimension(25, 25));
        prevPageButton.setMinimumSize(new java.awt.Dimension(20, 25));
        prevPageButton.setPreferredSize(new java.awt.Dimension(25, 25));
        prevPageButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sleuthkit/autopsy/corecomponents/btn_step_back_hover.png"))); // NOI18N
        prevPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevPageButtonActionPerformed(evt);
            }
        });
        panelPageNextPrevButton.add(prevPageButton);

        nextPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sleuthkit/autopsy/corecomponents/btn_step_forward.png"))); // NOI18N
        nextPageButton.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.nextPageButton.text")); // NOI18N
        nextPageButton.setBorderPainted(false);
        nextPageButton.setContentAreaFilled(false);
        nextPageButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sleuthkit/autopsy/corecomponents/btn_step_forward_disabled.png"))); // NOI18N
        nextPageButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        nextPageButton.setMaximumSize(new java.awt.Dimension(25, 25));
        nextPageButton.setMinimumSize(new java.awt.Dimension(20, 25));
        nextPageButton.setPreferredSize(new java.awt.Dimension(25, 25));
        nextPageButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sleuthkit/autopsy/corecomponents/btn_step_forward_hover.png"))); // NOI18N
        nextPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPageButtonActionPerformed(evt);
            }
        });
        panelPageNextPrevButton.add(nextPageButton);

        jSepMed6.setPreferredSize(new java.awt.Dimension(5, 0));
        panelPageNextPrevButton.add(jSepMed6);

        controlPanel.add(panelPageNextPrevButton);

        panelGoToPage.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        goToPageLabel.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.goToPageLabel.text")); // NOI18N
        panelGoToPage.add(goToPageLabel);

        jSepSm1.setPreferredSize(new java.awt.Dimension(2, 0));
        panelGoToPage.add(jSepSm1);

        goToPageTextField.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.goToPageTextField.text")); // NOI18N
        goToPageTextField.setMaximumSize(new java.awt.Dimension(2147483647, 25));
        goToPageTextField.setMinimumSize(new java.awt.Dimension(50, 25));
        goToPageTextField.setPreferredSize(new java.awt.Dimension(70, 25));
        goToPageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToPageTextFieldActionPerformed(evt);
            }
        });
        panelGoToPage.add(goToPageTextField);

        jSepMed7.setPreferredSize(new java.awt.Dimension(5, 0));
        panelGoToPage.add(jSepMed7);

        controlPanel.add(panelGoToPage);

        panelScriptSelect.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        languageLabel.setText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.languageLabel.text")); // NOI18N
        languageLabel.setToolTipText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.languageLabel.toolTipText")); // NOI18N
        panelScriptSelect.add(languageLabel);

        jSepSm2.setPreferredSize(new java.awt.Dimension(2, 0));
        panelScriptSelect.add(jSepSm2);

        languageCombo.setToolTipText(org.openide.util.NbBundle.getMessage(StringsContentPanel.class, "StringsContentPanel.languageCombo.toolTipText")); // NOI18N
        languageCombo.setMinimumSize(new java.awt.Dimension(150, 25));
        languageCombo.setPreferredSize(new java.awt.Dimension(150, 25));
        languageCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageComboActionPerformed(evt);
            }
        });
        panelScriptSelect.add(languageCombo);

        controlPanel.add(panelScriptSelect);

        add(controlPanel, java.awt.BorderLayout.NORTH);

        outputViewPane.setEditable(false);
        outputScrollPane.setViewportView(outputViewPane);

        add(outputScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void languageComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageComboActionPerformed
        if (dataSource != null) {
            setDataView(dataSource, currentOffset);
        }
    }//GEN-LAST:event_languageComboActionPerformed

    private void goToPageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToPageTextFieldActionPerformed
        String pageNumberStr = goToPageTextField.getText();
        int pageNumber;
        int maxPage = Math.round((dataSource.getSize() - 1) / PAGE_LENGTH) + 1;
        try {
            pageNumber = Integer.parseInt(pageNumberStr);
        } catch (NumberFormatException ex) {
            pageNumber = maxPage + 1;
        }
        if (pageNumber > maxPage || pageNumber < 1) {
            JOptionPane.showMessageDialog(this,
                    NbBundle.getMessage(this.getClass(),
                            "StringsTextViewer.goToPageTextField.msgDlg",
                            maxPage),
                    NbBundle.getMessage(this.getClass(),
                            "StringsTextViewer.goToPageTextField.err"),
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        currentOffset = (pageNumber - 1) * PAGE_LENGTH;
        currentPage = pageNumber;
        currentPageLabel.setText(Integer.toString(currentPage));
        setDataView(dataSource, currentOffset);
    }//GEN-LAST:event_goToPageTextFieldActionPerformed

    private void prevPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevPageButtonActionPerformed
        //@@@ this is part of the code dealing with the data viewer. could be copied/removed to implement the scrollbar
        currentOffset -= PAGE_LENGTH;
        currentPage -= 1;
        currentPageLabel.setText(Integer.toString(currentPage));
        setDataView(dataSource, currentOffset);
    }//GEN-LAST:event_prevPageButtonActionPerformed

    private void nextPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageButtonActionPerformed
        //@@@ this is part of the code dealing with the data viewer. could be copied/removed to implement the scrollbar
        currentOffset += PAGE_LENGTH;
        currentPage += 1;
        currentPageLabel.setText(Integer.toString(currentPage));
        setDataView(dataSource, currentOffset);
    }//GEN-LAST:event_nextPageButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JLabel currentPageLabel;
    private javax.swing.JLabel goToPageLabel;
    private javax.swing.JTextField goToPageTextField;
    private javax.swing.JComboBox<SCRIPT> languageCombo;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JButton nextPageButton;
    private javax.swing.JLabel ofLabel;
    private javax.swing.JScrollPane outputScrollPane;
    private javax.swing.JTextPane outputViewPane;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JLabel pageLabel2;
    private javax.swing.JPanel panelScriptSelect;
    private javax.swing.JButton prevPageButton;
    private javax.swing.JPopupMenu rightClickMenu;
    private javax.swing.JMenuItem selectAllMenuItem;
    private javax.swing.JLabel totalPageLabel;
    // End of variables declaration//GEN-END:variables

    @Messages({
        "StringContentPanel_Loading_String=Loading text..."
    })

    /**
     * Sets the DataView (The tabbed panel)
     *
     * @param dataSource the content that want to be shown
     * @param offset     the starting offset
     */
    void setDataView(Content dataSource, long offset) {

        if (worker != null) {
            worker.cancel(true);
            worker = null;
        }

        if (dataSource == null) {
            return;
        }

        worker = new ContentWorker(dataSource, offset);
        outputViewPane.setText(Bundle.StringContentPanel_Loading_String());
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        worker.execute();
    }

    void setDataView(StringContent dataSource) {
        if (worker != null) {
            worker.cancel(true);
            worker = null;
        }

        if (dataSource == null) {
            return;
        }

        worker = new StringContentWorker(dataSource);
        outputViewPane.setText(Bundle.StringContentPanel_Loading_String());
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        worker.execute();
    }


    /**
     * Swingworker for getting the text from a content object.
     */
    private final class ContentWorker extends SwingWorker<String, Void> {

        private final Content content;
        private final long offset;

        /**
         * ContentWorker constructor
         *
         * @param content Content to get text from.
         * @param offset  The starting offset.
         */
        ContentWorker(Content content, long offset) {
            this.content = content;
            this.offset = offset;
        }

        @Override
        protected String doInBackground() throws Exception {
            int bytesRead = 0;
            // set the data on the bottom and show it

            if (content.getSize() > 0) {
                try {
                    bytesRead = content.read(data, offset, PAGE_LENGTH); // read the data
                } catch (TskCoreException ex) {
                    logger.log(Level.WARNING, "Error while trying to show the String content.", ex); //NON-NLS
                }
            }
            String text;
            if (bytesRead > 0) {
                //text = DataConversion.getString(data, bytesRead, 4);
                final SCRIPT selScript = (SCRIPT) languageCombo.getSelectedItem();
                StringExtract stringExtract = new StringExtract();
                stringExtract.setEnabledScript(selScript);
                StringExtractResult res = stringExtract.extract(data, bytesRead, 0);
                text = res.getText();
                if (StringUtils.isBlank(text)) {
                    text = NbBundle.getMessage(this.getClass(),
                            "StringsTextViewer.setDataView.errorNoText", currentOffset,
                            currentOffset + PAGE_LENGTH);
                }
            } else {
                text = NbBundle.getMessage(this.getClass(), "StringsTextViewer.setDataView.errorText", currentOffset,
                        currentOffset + PAGE_LENGTH);
            }

            return text;
        }

        @Override
        public void done() {
            if (isCancelled()) {
                return;
            }

            try {
                if (isCancelled()) {
                    return;
                }
                String text = get();
                dataSource = content;

                // disable or enable the next button
                if (offset + PAGE_LENGTH < dataSource.getSize()) {
                    nextPageButton.setEnabled(true);
                } else {
                    nextPageButton.setEnabled(false);
                }

                if (offset == 0) {
                    prevPageButton.setEnabled(false);
                    currentPage = 1; // reset the page number
                } else {
                    prevPageButton.setEnabled(true);
                }

                int totalPage = Math.round((dataSource.getSize() - 1) / PAGE_LENGTH) + 1;
                totalPageLabel.setText(Integer.toString(totalPage));
                outputViewPane.setText(text); // set the output view
                outputViewPane.moveCaretPosition(0);

                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

            } catch (InterruptedException | ExecutionException ex) {
                logger.log(Level.SEVERE, String.format("Failed to get text from content (id=%d)", content.getId()), ex);
            }
        }
    }

    /**
     * SwingWorker for getting the text from a StringContent object.
     */
    private final class StringContentWorker extends SwingWorker<String, Void> {

        private final StringContent content;

        /**
         * Constructor to pulling the text out of a string content object.
         *
         * @param content
         */
        StringContentWorker(StringContent content) {
            this.content = content;
        }

        @Override
        protected String doInBackground() throws Exception {
            return content.getString();
        }

        @Override
        public void done() {
            if (isCancelled()) {
                return;
            }

            try {
                String text = get();

                dataSource = null;
                nextPageButton.setEnabled(false);
                prevPageButton.setEnabled(false);
                currentPage = 1;

                outputViewPane.setText(text); // set the output view
                outputViewPane.moveCaretPosition(0);
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

            } catch (InterruptedException | ExecutionException ex) {
                logger.log(Level.SEVERE, String.format("Failed to get text from StringContent"), ex);
            }
        }
    }
}
