/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.filequery;

import java.awt.GridBagConstraints;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author wschaefer
 */
public class VideoThumbnailViewer extends javax.swing.JPanel {

    private int nextRow = 0;

    /**
     * Creates new form VideoThumbnailViewer
     */
    public VideoThumbnailViewer() {
        initComponents();
    }

    void clearViewer(){
        nextRow = 0;
        this.removeAll();
    }
    
    void addRow(List<Image> thumbnails, String fileInfo) {
        SwingUtilities.invokeLater(() -> {
            GridBagConstraints gridBagConstraints = new GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.weightx = 1.0;
            gridBagConstraints.weighty = 1.0;
            gridBagConstraints.anchor = GridBagConstraints.LINE_START;
            synchronized (this) {
                gridBagConstraints.gridy = nextRow;
                nextRow++;
            }
            this.add(new ThumbnailPanel(thumbnails, fileInfo), gridBagConstraints);
            System.out.println("ROW ADDED");
            revalidate();
            repaint();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
