/*
 * Autopsy Forensic Browser
 *
 * Copyright 2011-2017 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obt ain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sleuthkit.autopsy.communications;

import java.beans.PropertyChangeEvent;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;
import org.sleuthkit.autopsy.corecomponents.DataContentPanel;
import org.sleuthkit.autopsy.corecomponents.DataResultPanel;
import org.sleuthkit.autopsy.corecomponents.TableFilterNode;
import org.sleuthkit.datamodel.TskCoreException;

/**
 * The right hand side of the CVT. Has a DataResultPanel to show messages and
 * account details, and a Content viewer to show individual
 */
final class MessageBrowser extends javax.swing.JPanel implements ExplorerManager.Provider {

    private static final long serialVersionUID = 1L;

    private ExplorerManager parentExplorereManager;
    private final DataContentPanel customContentView;
    private final DataResultPanel messagesResultPanel;
    private ExplorerManager internalExplorerManager;

    MessageBrowser() {
        initComponents();
        customContentView = DataContentPanel.createInstance();
        messagesResultPanel = DataResultPanel.createInstanceUninitialized("Account", "", Node.EMPTY, 0, customContentView);
        splitPane.setTopComponent(messagesResultPanel);
        splitPane.setBottomComponent(customContentView);

    }

    @Override
    public void addNotify() {
        super.addNotify();
        this.parentExplorereManager = ExplorerManager.find(this);

        internalExplorerManager = new ExplorerManager();

        parentExplorereManager.addPropertyChangeListener((PropertyChangeEvent evt) -> {
            if (evt.getPropertyName().equals(ExplorerManager.PROP_SELECTED_NODES)) {
                final Node[] selectedNodes = parentExplorereManager.getSelectedNodes();
                switch (selectedNodes.length) {
                    case 0:
                      messagesResultPanel.setNode(null);
                        break;
                    case 1:
                        final Node selectedNode = selectedNodes[0];
                        if (selectedNode instanceof AccountDeviceInstanceNode) {
                            try {
                                final AccountDetailsNode accountDetailsNode = new AccountDetailsNode((AccountDeviceInstanceNode) selectedNode);
                                messagesResultPanel.setNode(new TableFilterNode(accountDetailsNode, true));
                            } catch (TskCoreException ex) {
                                Exceptions.printStackTrace(ex);
                            }
                        } else {
                            internalExplorerManager.setRootContext(selectedNode);
                        }
                        break;
                    // TODO: fill in multiseelct support
                    default:
                        break;
                }
            }
        });
        messagesResultPanel.open();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public ExplorerManager getExplorerManager() {
        return internalExplorerManager;
    }
}
