/*
 * Autopsy
 *
 * Copyright 2020 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sleuthkit.autopsy.discovery.ui;

import java.util.List;
import org.sleuthkit.autopsy.discovery.search.AbstractFilter;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.event.ListSelectionListener;
import org.openide.util.NbBundle;
import org.sleuthkit.autopsy.coreutils.ThreadConfined;
import org.sleuthkit.autopsy.discovery.search.SearchData;
import org.sleuthkit.autopsy.discovery.search.SearchFiltering.ArtifactTypeFilter;
import org.sleuthkit.autopsy.guiutils.CheckBoxListPanel;
import org.sleuthkit.datamodel.BlackboardArtifact;

/**
 * Filter for selection of a specific Artifact type to limit results to.
 */
final class ArtifactTypeFilterPanel extends AbstractDiscoveryFilterPanel {

    private static final long serialVersionUID = 1L;
    private static final CheckBoxListPanel<BlackboardArtifact.ARTIFACT_TYPE> artifactList = new CheckBoxListPanel<>();

    /**
     * Creates new form ArtifactTypeFilterPanel
     */
    @ThreadConfined(type = ThreadConfined.ThreadType.AWT)
    ArtifactTypeFilterPanel() {
        initComponents();
        setUpArtifactTypeFilter();
        add(artifactList);
    }

    /**
     * Initialize the data source filter.
     */
    @ThreadConfined(type = ThreadConfined.ThreadType.AWT)
    private void setUpArtifactTypeFilter() {
        artifactList.clearList();
        for (BlackboardArtifact.ARTIFACT_TYPE artifactType : SearchData.Type.DOMAIN.getArtifactTypes()) {
            artifactList.addElement(artifactType.getDisplayName(), null, artifactType);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        artifactTypeCheckbox = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(artifactTypeCheckbox, org.openide.util.NbBundle.getMessage(ArtifactTypeFilterPanel.class, "ArtifactTypeFilterPanel.artifactTypeCheckbox.text")); // NOI18N
        artifactTypeCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artifactTypeCheckboxActionPerformed(evt);
            }
        });

        setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void artifactTypeCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artifactTypeCheckboxActionPerformed
        artifactList.setEnabled(artifactTypeCheckbox.isSelected());
    }//GEN-LAST:event_artifactTypeCheckboxActionPerformed

    @ThreadConfined(type = ThreadConfined.ThreadType.AWT)
    @Override
    void configurePanel(boolean selected, int[] indicesSelected) {
        artifactTypeCheckbox.setSelected(selected);
        if (artifactTypeCheckbox.isEnabled() && artifactTypeCheckbox.isSelected()) {
            artifactList.setEnabled(true);
//            if (indicesSelected != null) {
//                artifactList.setSelectedIndices(indicesSelected);
//            }
        } else {
            artifactList.setEnabled(false);
        }
    }

    @ThreadConfined(type = ThreadConfined.ThreadType.AWT)
    @Override
    JCheckBox getCheckbox() {
        return artifactTypeCheckbox;
    }

    @Override
    JLabel getAdditionalLabel() {
        return null;
    }

    @ThreadConfined(type = ThreadConfined.ThreadType.AWT)
    @NbBundle.Messages({"ArtifactTypeFilterPanel.selectionNeeded.text=At least one Result type must be selected."})
    @Override
    String checkForError() {
        if (artifactTypeCheckbox.isSelected() && artifactList.getSelectedElements().isEmpty()) {
            return Bundle.ArtifactTypeFilterPanel_selectionNeeded_text();
        }
        return "";
    }

    @ThreadConfined(type = ThreadConfined.ThreadType.AWT)
    @Override
    AbstractFilter getFilter() {
        if (artifactTypeCheckbox.isSelected() && isFilterSupported()) {
            List<BlackboardArtifact.ARTIFACT_TYPE> artifactTypeList = artifactList.getSelectedElements();
            return new ArtifactTypeFilter(artifactTypeList);
        }
        return null;
    }

    @ThreadConfined(type = ThreadConfined.ThreadType.AWT)
    @Override
    void removeListeners() {
        super.removeListeners();
        if (artifactList != null) {
            for (ListSelectionListener listener : getListSelectionListeners()) {
                artifactList.removeListSelectionListener(listener);
            }
        }
    }

    @Override
    ListSelectionListener[] getListSelectionListeners() {
        return artifactList.getListSelectionListeners();
    }

    @Override
    void addListSelectionListener(ListSelectionListener listener) {
        artifactList.addListSelectionListener(listener);
    }

    @Override
    void removeListSelectionListener(ListSelectionListener listener) {
        artifactList.removeListSelectionListener(listener);
    }

    @Override
    boolean isFilterSupported() {
        return !artifactList.isEmpty();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox artifactTypeCheckbox;
    // End of variables declaration//GEN-END:variables
}
