/*
 * Autopsy Forensic Browser
 *
 * Copyright 2014 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sleuthkit.autopsy.ingest;

/**
 * A UI panel that allows a user to make data source ingest cancellation
 * requests.
 */
final class DataSourceIngestCancellationPanel extends javax.swing.JPanel {

    enum CancelRequestType {

        CURRENT_DATA_SOURCE_MODULE, DATA_SOURCE_INGEST, JOB
    }

    private CancelRequestType requestType;

    /**
     * Constructs an instance of the panel.
     */
    DataSourceIngestCancellationPanel() {
        initComponents();
        this.cancelCurrentModuleRadioButton.setSelected(true);
        this.requestType = DataSourceIngestCancellationPanel.CancelRequestType.CURRENT_DATA_SOURCE_MODULE;
    }

    /**
     * Gets the cancellation request type.
     *
     * @return An enumeration member indicating the request type.
     */
    DataSourceIngestCancellationPanel.CancelRequestType getCancelRequest() {
        return this.requestType;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelRadioButtonsGroup = new javax.swing.ButtonGroup();
        cancelCurrentModuleRadioButton = new javax.swing.JRadioButton();
        cancelDataSourceIngestRadioButton = new javax.swing.JRadioButton();
        cancelIngestJobRadioButton = new javax.swing.JRadioButton();

        cancelRadioButtonsGroup.add(cancelCurrentModuleRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(cancelCurrentModuleRadioButton, org.openide.util.NbBundle.getMessage(DataSourceIngestCancellationPanel.class, "DataSourceIngestCancellationPanel.cancelCurrentModuleRadioButton.text")); // NOI18N
        cancelCurrentModuleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCurrentModuleRadioButtonActionPerformed(evt);
            }
        });

        cancelRadioButtonsGroup.add(cancelDataSourceIngestRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(cancelDataSourceIngestRadioButton, org.openide.util.NbBundle.getMessage(DataSourceIngestCancellationPanel.class, "DataSourceIngestCancellationPanel.cancelDataSourceIngestRadioButton.text")); // NOI18N
        cancelDataSourceIngestRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDataSourceIngestRadioButtonActionPerformed(evt);
            }
        });

        cancelRadioButtonsGroup.add(cancelIngestJobRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(cancelIngestJobRadioButton, org.openide.util.NbBundle.getMessage(DataSourceIngestCancellationPanel.class, "DataSourceIngestCancellationPanel.cancelIngestJobRadioButton.text")); // NOI18N
        cancelIngestJobRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelIngestJobRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelIngestJobRadioButton)
                    .addComponent(cancelDataSourceIngestRadioButton)
                    .addComponent(cancelCurrentModuleRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelCurrentModuleRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelDataSourceIngestRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelIngestJobRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelCurrentModuleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCurrentModuleRadioButtonActionPerformed
        this.requestType = DataSourceIngestCancellationPanel.CancelRequestType.CURRENT_DATA_SOURCE_MODULE;
    }//GEN-LAST:event_cancelCurrentModuleRadioButtonActionPerformed

    private void cancelDataSourceIngestRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDataSourceIngestRadioButtonActionPerformed
        this.requestType = DataSourceIngestCancellationPanel.CancelRequestType.DATA_SOURCE_INGEST;
    }//GEN-LAST:event_cancelDataSourceIngestRadioButtonActionPerformed

    private void cancelIngestJobRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelIngestJobRadioButtonActionPerformed
        this.requestType = DataSourceIngestCancellationPanel.CancelRequestType.JOB;
    }//GEN-LAST:event_cancelIngestJobRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cancelCurrentModuleRadioButton;
    private javax.swing.JRadioButton cancelDataSourceIngestRadioButton;
    private javax.swing.JRadioButton cancelIngestJobRadioButton;
    private javax.swing.ButtonGroup cancelRadioButtonsGroup;
    // End of variables declaration//GEN-END:variables
}
