/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.keywordsearch;

import java.util.logging.Level;
import java.util.logging.Logger;

final class KeywordSearchOptionsPanel extends javax.swing.JPanel {

    //private final KeywordSearchOptionsPanelController controller;
    //private static KeywordSearchOptionsPanel instance = null;
    private static final Logger logger = Logger.getLogger(KeywordSearchOptionsPanel.class.getName());
    private KeywordSearchConfigurationPanel1 panel1;
    private KeywordSearchConfigurationPanel3 panel3;
    private KeywordSearchConfigurationPanel2 panel2;

    KeywordSearchOptionsPanel() {//KeywordSearchOptionsPanelController controller) {
        //this.controller = controller;
        initComponents();
        customizeComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }
    
    /*public static KeywordSearchOptionsPanel getDefault() {
        if(instance == null) {
            instance = new KeywordSearchOptionsPanel();
        }
        return instance;
    }*/
    
    private void customizeComponents() {
        setName("Advanced Keyword Search Configuration");
        panel1 = new KeywordSearchConfigurationPanel1();
        panel3 = new KeywordSearchConfigurationPanel3();
        panel2 = new KeywordSearchConfigurationPanel2();
        tabbedPane.insertTab("Lists", null, panel1, "List configuration", 0);
        tabbedPane.insertTab("Languages", null, panel3, "Languages configuration", 1);
        tabbedPane.insertTab("General", null, panel2, "General configuration", 2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        logger.log(Level.WARNING, "----->KEYWORD LOAD<-----");
        // Deselect all table rows
        panel1.listsManagementPanel.reload();
        // Reload the XML to avoid 'ghost' vars
        KeywordSearchListsXML.getCurrent().reload();
    }

    void store() {
        logger.log(Level.WARNING, "----->KEYWORD STORE<-----");
        KeywordSearchListsXML.getCurrent().save();
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
